server:
  port: 8081
application:
  fe: http://localhost:4200
default-users:
  password: default_password
key:
  access-token-expired: 30 #days
  refresh-token-expired: 90 #days
  jwt-secret: default_secret
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EdwKaiTwra
    username: root
    password: mynewpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
      platform: mysql
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: mymail@gmail.com
    password: mypass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false