server:
  port: 8081
application:
  fe: http://localhost:4200
default-users:
  password: 3w3P!!_-@A
key:
  access-token-expired: 30 #days
  refresh-token-expired: 90 #days
  jwt-secret: R2[l%+<6NK]a+?Z+T-ey05Vma,@P-1+rVRv9c/Q3(I7*+G&Cl4)xFG|kN5~5gFob
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EdwKaiTwra
    username: root
    password: mynewpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
      platform: mysql
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: edwkaitwrateam@gmail.com
    password: mtgfiykdlsnnppmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false